service: quizApp-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

functions:
  app:
    handler: src/app.handler
    events:
      - http:
          path: /
          method: get
          cors: true

package:
  exclude:
    - node_modules/**
